### ISSUE TITLE
INFORMATIONS VSTREAM PREMIUM

### ISSUE THREAD

**Issue by stefane31** [ludopotte/vStream#151]
Bonjour Ludopotte,

Une petite question....quelle est la différence entre vstream et vstream premium?
Merci pour ta réponse.

Stefane31

**Comment by ludopotte** [comment]
Bonjour stefane31,

La différence entre vStream et vStream Premium est que la Version Premium est patchée (Mise à Jour 2 fois par Mois) pour que les Gens ont la dernière version de vStream à Jour directement.

**Comment by stefane31** [comment]
Merci pour ta réponse.
