### ISSUE TITLE
(PATCH VSTREAM)

### ISSUE THREAD

**Issue by ludopotte** [ludopotte/vStream#181]
Informations du Patch fait sur la Version 0.7.8 si-dessous :
Changement des Fichiers de l'Extension du 06 Avril 2020
Patch en Fichier Zip à télécharger au 
https://github.com/ludopotte/vStream/
ou sur Discord, Rubrique "vstream" 
au https://discord.gg/Sr7Cusj

**Comment by bala64** [comment]
Bonjour,
Je suis sur Mac OS avec Kodi v18.6 Leia
J'ai installé repository.vstream-0.0.3 puis patch.vstream-0.7.8.1 mais j'ai toujours le message d'erreur suivant : vstream error (check the log for more information)
Pouvez-vous m'aider svp ? Merci d'avance

**Comment by ludopotte** [comment]
Ok et voici 2 Méthodes pour installer vStream et son Patch si-dessous :
Méthode 1 : Installez l'Extension au https://github.com/ludopotte/vStream
ou directement depuis Kodi avec Github Browser
au https://github.com/tvaddonsco/tva-release-repo/tree/master/plugin.git.browser
et ensuite allez dans "Search by GitHub Username" et tapez "ludopotte".
Méthode 2 : Téléchargez la Version Beta au https://github.com/Kodi-vStream/venom-xbmc-addons
en cliquant sur le Bouton "Clone or download" et appuyez sur le Bouton "Download Zip".
Ensuite ouvrez le fichier et compressez le Dossier "plugin.video.vstream" avec Winzip
et renommez le en "patch.vstream". Apres installez ce Fichier manuellement sur Kodi
à l'aide d'une clé USB, d'une Carte SD ou d'une Carte Micro SD.

**Comment by bala64** [comment]
j'ai vu ce tutoriel avant de vous poser la question, j'ai fait plusieurs tentatives depuis hier, 
voici les étapes qui j'ai suivi 
1. installer from zip file le dépôt de l'extension vstream 0.0.3
2. installer from repository l'addon vstream 0.7.8
3. installer from zip file le patch 0.7.8.1
au final j'ai l'addon qui est bien installé mais lorsque je le lance, j'ai le message d'erreur signalé.
N'y a t-il pas un problème général ?

**Comment by ludopotte** [comment]
@bala64 Si tu veux parler de ton problème avec moi, fais le sur Discord au https://discord.gg/Sr7Cusj

**Comment by bala64** [comment]
après recherche, cela fonctionne en installant une ancienne version, puis en faisant la mise à jour
lien ci-dessous : 
https://github.com/Kodi-vStream/venom-xbmc-addons/releases/tag/0.7.7

**Comment by mirsa68100** [comment]
Salut. Ça sert à quoi ce patch svp ?
Merci
