### ISSUE TITLE
PATCH VSTREAM

### ISSUE THREAD

**Issue by ludopotte** [ludopotte/vStream#229]
Patch en Fichier Zip à télécharger au 
https://github.com/ludopotte/vStream/
ou sur Discord, Rubrique "vstream" 
au https://discord.gg/Sr7Cusj

**Comment by Miknotdoc** [comment]
Bonjour à toi ! A quoi sert le patch ? Je l'ai installé ainsi le plug-in.video.vstream.0.8.0

**Comment by ludopotte** [comment]
Bonjour, mon Patch sert a avoir vStream à jour quotidiennement

**Comment by Miknotdoc** [comment]
Ah d'accord, donc ça se fait automatiquement ? Je voulais savoir au sujet du lien hoster sur exteme down, tu sais comment arranger ça ?
En tout cas, c'est super ce que tu fais ! Merci

**Comment by ludopotte** [comment]
Concernant extreme down, faut que lise bien ce qui est marquer sur vStream et ça réglera peut être ton problème du lien hoster sinon je regarderais ça.
