### ISSUE TITLE
PATCH VS BETA

### ISSUE THREAD

**Issue by alKODIque** [ludopotte/vStream#252]
Bonjour @ludopotte 

Lorsque  j"installe la nouvelle beta sur le depot de vstream, je n'ai plus aucun lien, d'aucune source (peu importe laquelle) qui fonctionne.  Par contre, lorsque j'installe ton patch, tout se remet a fonctionner de nouveau.  Ma question est: que fais-tu de different que les developpeurs de vstream ne font pas pour obtenir ce resultat?

Je suis sous nvidia shield, kodi 18.7

Merci!

**Comment by alKODIque** [comment]
J'ai oublié de mensionner que je possède un compte premium uptobox que j'ai intégrer a vstream ainsi que ALLDEBRID. Donc je fais passer mes liens par urlresolver

**Comment by ludopotte** [comment]
Mon Patch vient de la Beta que j'ouvre en prenant le dossier "plugin.video.vstream"
