### ISSUE TITLE
RAJOUTS DE NOUVELLES SOURCES

### ISSUE THREAD

**Issue by ludopotte** [ludopotte/vStream#310]
Informations du Patch fait sur la Version 0.8.2 si dessous :
Changement des Fichiers de l'Extension du 16 Novembre 2020
Patch en Fichier Zip à télécharger au  
https://github.com/ludopotte/vStream/
ou sur Discord au https://discord.gg/S65HBXm

**Comment by milkibreizh** [comment]
@ludopotte 

bon j'ai regardé pour les sites que tu a demandé helas je pense pas mettre les source sur vstream
car les sites ne sont plus mis a  jours depuis 2 semaines alors que j'allais les proposer.
c'est pour cela que je poste ici les sources car c'est toi qui les a demandé

elles seront mise sur vtream si les sites se reactivent

https://pastebin.com/qNggLQWE   fichier : serie_dpstreamhd.py
https://pastebin.com/K3aLspit        fichier : cinemey.py

il y a un problème avec la source cinemey sur la recherche de mot composé

tu dois mettre les deux fichiers renommée dans 
/Vstream/resources/sites/cinemey.py
/Vstream/resources/sites/serie_dpstreamhd.py

et pour la recherche globale edite le fichier avec les id plugin_cinemey plugin_serie_dpstreamhd
rajouter les deux lignes

```
 <!--activation invisible des sources -->
		<setting visible="false" id="plugin_cinemey" type="bool" label="Cinemey" default="true"/>
		<setting visible="false" id="plugin_serie_dpstreamhd" type="bool" label="Serie Dpstreamhd" default="true"/>
                <setting visible="false" id="plugin_adkami_com" type="bool" label="ADKami" default="true"/>
                 <setting visible="false" id="plugin_alldebrid" type="bool" label="AllDebrid" default="true"/>
                <setting visible="false" id="plugin_allfilms" type="bool" label="All Films" default="true"/>

```
je ferais sans doute pareil pour la source cine car par contre je suis pas sur qu'elle soit accepté
si jamais je la fais
si tu as un soucis j'ai souscris à cette issue  ......voila bonne continuation

**Comment by ludopotte** [comment]
Ok merci mon Cher

**Comment by milkibreizh** [comment]
je peux pas la proposer en source car  le site n'est plus mis a jour
apres c'est un critère de sélection subjectif elle pourrait intéresser en effet d'autre personne
de plus si je la mets dans vstream je dois procéder a un lefting du code pour qu'il
soit correctement lisible pour ceux qui voudrais corriger un bug ,je peux pas
la mettre dans l'etat dans vstream même si elle fonctionne
je surveille de toute facon pour voir si le site se met a jour et n’hésite pas à me remonter des bugs
a+

**Comment by ludopotte** [comment]
Merci @milkibreizh pour ses Sources mais la recherche globale ne marche pas et je sais pas ou il faut ajouter les lignes de code pour la recherche globale. Peux-tu m'aider ?

**Comment by milkibreizh** [comment]
oui en effet les sources n'ont pas été mis a jour pendant un moi
et je viens de constater que le site à mis de nouveaux fichier s
mais il y a seulement deux jours

il faut modifier le fichier settings.xml

dans le répertoire de vstream w10 
C:\Users\ludopotte \AppData\Roaming\Kodi\addons\plugin.video.vstream\resources\settings.xml


dans le github je te montres ou^ il est mais il ne faut pas l’éditer bien sur^^
https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/settings.xml

attention ce fichier est vital et doit être lisible sans erreur car il 
mémorise l'essentiel des données qui doivent être sauvegardée pour redémarrer une session


regarde le fichier dans le fichier setting il y a une section activation invisible des sources 

```
<!--activation invisible des sources -->
<setting visible="false" id="plugin_adkami_com" type="bool" label="ADKami" default="true"/>

<setting visible="false" id="plugin_alldebrid" type="bool" label="AllDebrid" default="true"/>

<setting visible="false" id="plugin_animecomplet" type="bool" label="Animecomplet" default="true"/>

```

remarque
_setting visible="false_" est toujours 

_id="plugin_alldebrid"_  on ajoute plugin_ + nom du fichier sans .py (SITE_IDENTIFIER)

_type="bool_ non modifiable c'est quand tu as la petite croix ou non

_label="AllDebrid"_ c'est le nom que tu as dans SITE_NAME

### Exemple rajouter un fichier pour la recherche globale

cinemey.py
exemple pour cinemey quand je créé un fichier c'est un fichier py nommé cinemey.py
je mets le nom du fichier
SITE_IDENTIFIER = 'cinemey'
je met le label
SITE_NAME = 'Cinemey'
....site desc.....et ca on s'en fout un peu mais c'est la description que tu as dans le menu global
SITE_DESC = 'Films VF & VOSTFR en streaming.'

je dois rajouter 
`<setting visible="false" id="plugin_cinemey" type="bool" label="Cinemey" default="true"/>`
        
ya que deux variables à changer et autrement c'est tjrs les mêmes  valeurs dans les lignes qui correspondent aux sites
id="plugin_cinemey"
label="Cinemey"

pareil pour serie dpstreamhd je prens id="plugin_SITE_IDENTIFIER"  et label ="SITE_NAME"
`<setting visible="false" id="plugin_serie_dpstreamhd" type="bool" label="Serie Dpstreamhd" default="true"/>`

il faut placer ensuite ces deux lignes dans le fichier par ordre alphabétique

source  settings.xml à placer au bon endroit
https://pastebin.com/9iJrimdD

une mise à jour des fichiers pastbin est obligatoire  car les sources  sont non compatibles 
avec la version récente de vstream  pour la requete de la recherche
cinemey.py
https://pastebin.com/K3aLspit
serie_dpstreamhd.py
https://pastebin.com/qNggLQWE

bonus 
https://pastebin.com/6JvZjgFs

sur ceux bon soirée et doucement

**Comment by ludopotte** [comment]
Merci pour tes Nouvelles Sources, je les ai mis dans mon Patch avec leurs Logos disponible au https://github.com/ludopotte/vStream/releases/tag/patchvstream

**Comment by milkibreizh** [comment]
sauf que je t'avais précisé qu'il faut eviter de partager la source cine974
le mec a le droit de porter plainte contrairement aux autres sites ou
il n'est pas précisé les ayant droit vis a vis des données
(normale se sont des sites a la limite de la legalité )

**Comment by ludopotte** [comment]
Ok j'ai enlever Cine974 de vstream et aussi de mon patch.

**Comment by milkibreizh** [comment]
comme je precisais tu peux faire le pr mais tu dois signaler l'information qu'il y a sur le site concernant les données
après ce seras validé ou pas je peux pas savoir

**Comment by ludopotte** [comment]
Ok mais pour plus de précaution, j'ai supprimer la création de la Source Cine974 sur vStream et aussi sur mon patch car je veux pas de problème, c'est mieux.

**Comment by milkibreizh** [comment]
c'est pas bien grave mais tu pouvais tenté comme même
ce genre de truc ya que tmpname ou arias qui peuvent décider
ou j'en est peu etre fait tout un fromage

_Base de données :
Les bases de données figurant sur le site Internet sont protégées par les dispositions de la loi du 11 juillet 1998 portant transposition dans le Code de la propriété intellectuelle (CPI) de la directive européenne du 11 mars 1996 relative à la protection juridique des bases de données. Sont notamment interdites l'extraction et la réutilisation, quantitativement ou qualitativement substantielles, du contenu des bases de données contenues sur ce site Internet. Tout contrevenant s'expose aux sanctions visées aux articles L 343-1 et suivants du Code de la propriété intellectuel_

ca calme.....un peu ...j'ai plus peur des petits sites que des gros car ici c'est des passionées qui font le sites
et si ils ne sont pas content ils risquent de bouger leurs culs..tandis que les plus gros sites..
tous le monde en a rien a foutres

**Comment by ludopotte** [comment]
Oui c'est sur mais je prends la Sécurité. Si tu es sur Discord, je t'expliquerais ce que j'ai fait en privé par rapport aux sources que tu m'as donner ok ?

**Comment by milkibreizh** [comment]
par contre j'oubliais de te dire un chose importante il faut toujours verifier si un site est stable avant de faire un pr
c'est a dire voir comment il evoluent sur une ou deux semaines..et il faut nettoyer les sources
avant de faire le pr car ya razorex qui epluche tout les petits détails et cela lui fait du boulot supplémentaires
...mais bon c'est fait

**Comment by milkibreizh** [comment]
quate en meme posté temps

**Comment by milkibreizh** [comment]
non mais le truc c'est que discord facebook et compagnie c'est pas mon truc

**Comment by milkibreizh** [comment]
par contre au lieu que tu poste une source sans savoir comment cela fonctionne je peux t'expliqué
ou t'apprendre quelque trucs si tu veux faire une source toi meme

**Comment by ludopotte** [comment]
Ok ca marche. Je peux le faire mon Patch avec Ciné 974 mais en privé, c'est ca ?

**Comment by milkibreizh** [comment]
evidement mais comme je te le disais on s'en fait peu etre un gros fromage
et tu ne risques rien faisant un pr avec les explications que j'ai cité ci dessus

**Comment by sizanic** [comment]
> Ok ca marche. Je peux le faire mon Patch avec Ciné 974 mais en privé, c'est ca ?

Salut @ludopotte 

Tant que privé veut bien dire que tu le gardes chez toi, pour toi.

Et tant que ce patch de vStream qui contient désormais des sources non développées par la team vStream n'est pas celle qui est annoncée sur le discord officielle de vStream.
Cela pourrait être trompeur pour des personnes qui vont alors télécharger ce patch et être persuadé d'utiliser une vrai version de vStream.
Cette version modifiée de vStream finira alors dans la nature.
Et si il y a vraiment un problème avec de la diffusion de contenu protégé, c'est nous qu'on va venir voir.

Si tu veux modifier vStream et diffuser cette version modifiée, tu ne peux pas l'appeler vStream, ce n'est pas vStream.
Et tu ne pourras pas utiliser un canal officiel de vStream pour la diffuser.

**Comment by ludopotte** [comment]
Le Patch qui respecte vStream que j'ai créer s'appelle "beta.vstream-..." et contient les fichiers qui sont fait par la Team vStream. Mon Patch est pas diffuser sur le Discord Officiel de vStream mais le Patch Beta oui.

**Comment by sizanic** [comment]
OK

C'est que j'ai du mal à suivre.

Il y a donc donc versions : 
- Une "beta.vstream" qui est annoncée sur le Discord et qui est accessible sur ce github.
- Ton "Patch" qui est une version modifiée de vStream et qui n'est pas visible, ni sur Discord, ni sur ce github.

C'est bien ça ?

**Comment by ludopotte** [comment]
Oui c'est bien ca @sizanic
