### ISSUE TITLE
BETA VSTREAM 0.8.6.02.2021

### ISSUE THREAD

**Issue by ludopotte** [ludopotte/vStream#386]
Informations du Patch fait sur la Version 0.8.6 si dessous :
Mise à Jour des Fichiers de Fevrier 2021
Beta en Fichier Zip à télécharger au  
https://github.com/ludopotte/vStream/ 
et sur Discord au https://discord.gg/S65HBXm

**Comment by Miknotdoc** [comment]
Bonjour, il y a un problème au moment de l'installation, problème indigo, indisponible sur cette version de kodi.
Que faire ?
Merci d'avance

**Comment by ludopotte** [comment]
Sur Kodi 19 - Matrix, Indigo ne fonctionne pas donc il faut réinstaller Kodi 18.9- Leia pour l'instant.

**Comment by sizanic** [comment]
@Miknotdoc 

Oui, Indigo n'est pas disponible pour kodi 19.
Mais si tu cherches juste à installer vStream, tu n'as pas besoin d'INDIGO.
vStream s'installe et est compatible avec KODI 19. (sans indigo)
