### ISSUE TITLE
VSTREAM SUR STUBE TV

### ISSUE THREAD

**Issue by ludopotte** [ludopotte/vStream#426]
vStream est disponible sur Stube TV sous Android au https://bit.ly/vstreamstubetv

**Comment by Miknotdoc** [comment]
Bonjour à toi, super top ton application surtout pour l'iptv mais je voudrais savoir comment mettre le films, séries en français ? Merci d'avance et encore bravo à toi !

**Comment by ludopotte** [comment]
Boonjour @Miknotdoc pour avoir films, séries en francais avec les Extensions d'origine de Stube TV, deja va dans "Lecteur", ensuite "Langue" et apres mets French pour la Langue préférée pour l'audio. Pour les Sous-Titres, choisi French pour la Langue préférée pour les sous-titres. Aprés, va sue "Extensions", "Installer depuis un dépot", ensuite clique sur "KODI-VAVOO-TV-Stube Repo", Sous-titres et ensuite "OpenSubtitles.org by OpenSubtitiles". Fait l'activation d'OpenSubtitles dans "Lecteur", Langue", "Sous-titres", "Services de téléchargement". Autre méthode pour avoir films et séries en francais, installe l'Extension vStream sur Stube TV.

**Comment by Miknotdoc** [comment]
Bonjour, impossible de faire mise à jour xstream 1.1.8 et l'urlresolver également, les chaînes tv ne fonctionnent plus.. Sais-tu la raison ? Ou pourrais-tu y regarder ?
Merci d'avance

**Comment by ludopotte** [comment]
Bonjour @Miknotdoc, pour xstream je sais pas la raison et pour UrlResolver n'est plus mis a jour car TV Addons est plus disponible en ce moment. Pour regarder les Chaines de TV, utilises plus l'Addon "Vavoo TV" dans Stube TV (ca marche mieux).
